services:
  api:
    build: ./api
    image: maplinedraw_api
    restart: always
    networks:
      - backend
    environment:
      - API_ROOT_PATH=/api
      - API_ALLOWED_ORIGIN="https://maplinedraw.com"
    volumes:
      - ./api/projects:/app/projects:rw
  web:
    build: ./web
    image: maplinedraw_web
    restart: always
    networks:
      - backend
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - STAGING=0
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=2048
      - ELLIPTIC_CURVE=secp256r1
      - USE_ECDSA=1
      - RENEWAL_INTERVAL=8d
      - DEBUG=0
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d:ro
    depends_on:
      - "api"
      - "web"

networks:
  backend:
  frontend:

volumes:
  letsencrypt:
    external: true
    name: letsencrypt
